### ISSUE TITLE
Getting started steps needs update for mainflux-cli

### ISSUE THREAD

**Issue by dramasamy** [absmach/supermq-docs#73]
**FEATURE REQUEST**

I'm trying to explore the 'mainflux' by installing it on a personal laptop and during that process, I felt that getting started documentation needs a minor update to increase the user experience. 

Also, there was an issue raised by the user before that they were not able to build the CLI because they tried without proper GOPATH and `go get`. 

I too faced the same issue; it's good to update the doc with more detailed steps for the new users.

Also, I found that the images and volumes should be deleted if the volumes were created by the old releases as that may not be compatible with the new version.

**Comment by drasko** [comment]
@dramasamy it is extremely important to find a good balance between good and useful Mainflux documentation and full-blown tutorial instructions for beginners.

Mainflux is intended for IoT operators, it is a complex distributed system and demands a minimum knowledge of the underlying technologies. People who want to compile Go programs themselves must learn about `GOPATH` on a basic Go courses.

I agree that documentation needs improvements, just not of that kind.

Also, are you planning to send a PR for this? You can do it with NOISSUE and discuss with the community on Gitter about these improvements. If PR is not planned, I would prefer that this issue is closed.

**Comment by drasko** [comment]
Ah, sorry - I just saw https://github.com/mainflux/docs/pull/74 :)
